title: Lab|208 (nome nao definitvo)
description: a descrição do site

theme: jekyll-theme-tactile

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
